### ISSUE TITLE
Plugin lässt sich nicht installieren bzw. nutzen

### ISSUE THREAD

**Issue by Davka** [marcelkipp/ePortfolio#109]
Es fehlt das Datenbankschema für das Plugin.

**Comment by asudau** [comment]
ist in arbeit, wollte das nicht unvollständig einchecken und mir war nicht klar dass wir schon soweit waren dass wir das from scratch irgendwo installieren wollen.. ist das mehr ein genereller hinweis oder braucht ihr das zeitnah?

**Comment by Davka** [comment]
Das Team bei uns würde es gern bei uns einmal installieren und testen. Vielleicht kannst du mir das Schema einmal per E-Mail zusenden, damit ich es testweise installieren kann.

**Comment by asudau** [comment]
leider wird das schema allein nicht reichen, da ausserdem noch veranstaltungekategorien mit bestimmten Konfigurationen dazu gehören.. aber ich seh zu, dass wir das fix nachrüsten!

**Comment by asudau** [comment]
https://github.com/marcelkipp/ePortfolio/commit/8a14f59962153779db38491da7907ceaf9decd1e  
https://github.com/marcelkipp/ePortfolio/commit/011e4414cbfe2d6abf720a08e673fd12464eb8dc  
https://github.com/marcelkipp/ePortfolio/commit/98ce2d21362f112caa06c1d4f5718f558dacc0b6  
https://github.com/marcelkipp/ePortfolio/commit/011e4414cbfe2d6abf720a08e673fd12464eb8dc  
https://github.com/marcelkipp/ePortfolio/commit/352955710cc39efdd16baa44cc1831c67e533e90
