### ISSUE TITLE
Prepared Statements

### ISSUE THREAD

**Issue by Davka** [marcelkipp/ePortfolio#110]
Sämtliche Datenbankanfragen sollten durch Prepared Statements ersetzt werden

bspw. https://github.com/marcelkipp/ePortfolio/blob/5b4e52878b99a52dbc35b299f4cbfa9341632661/controllers/settings.php#L167

**Comment by asudau** [comment]
$query = "SELECT id, title FROM mooc_blocks WHERE parent_id = :id";
        $statement = $db->prepare($query);
        $statement->execute(array(':id'=> $value[id]));
