### ISSUE TITLE
bootstrap und andere kollisionen mit studip layout

### ISSUE THREAD

**Issue by asudau** [marcelkipp/ePortfolio#114]
Testen und nachbessern

**Comment by Davka** [comment]
Die Schriftart wird immer überschrieben.

Wenn Bootstrap verwendet werden soll, dann ggf. eine angepasst Version von Boostrap.
![screenshot 2018-02-20 16 47 29](https://user-images.githubusercontent.com/1117697/36433821-c40fe8d6-165d-11e8-9909-f9690d0be5cd.png)

So muss es eigentlich aussehen

![screenshot 2018-02-20 16 47 58](https://user-images.githubusercontent.com/1117697/36433843-d1f907f2-165d-11e8-9ad7-2f7c84590aa6.png)

**Comment by asudau** [comment]
bootstrap ist jetzt erstmal raus..
