### ISSUE TITLE
4.0 Kompatibiltät

### ISSUE THREAD

**Issue by Davka** [marcelkipp/ePortfolio#118]
Wir werden zeitnah auf die 4.0 gehen, daher würd ich Methoden, die deprecated sind nicht verwenden..

'get_global_perm' => 'Use #{yellow:$GLOBALS[\'perm\']->get_perm()} instead',

**Comment by asudau** [comment]
also ich hätte da jetzt eh eher sowas gemacht:  
global $perm;  
$perm->have_perm('dozent')  
das sollte doch gehen oder? Tausche ich eben aus, da wo es benutzt wird..

**Comment by asudau** [comment]
https://develop.studip.de/trac/browser/branches/4.0/cli/studip40-compat.php

**Comment by asudau** [comment]
eigentlich ja 4.1

**Comment by asudau** [comment]
ist soweit ich das sehen kann abgeschlossen
