### ISSUE TITLE
Portfolio bearbeiten

### ISSUE THREAD

**Issue by Davka** [marcelkipp/ePortfolio#119]
Verursacht JS-Fehler

![screenshot 2018-02-20 17 03 44](https://user-images.githubusercontent.com/1117697/36434750-14099b3c-1660-11e8-89aa-752b88598fb0.png)
<img width="961" alt="screenshot 2018-02-20 17 04 05" src="https://user-images.githubusercontent.com/1117697/36434751-142ef18e-1660-11e8-9da2-c0a367fde075.png">

**Comment by Davka** [comment]
Brauch man Bootstrap unbedingt? Würde vermutlich einige Probleme sofort lösen, wenn es wegfliegen würde!

**Comment by asudau** [comment]
das ist soweit ich das erkennen kann behoben..
