### ISSUE TITLE
Portolio bearbeiten

### ISSUE THREAD

**Issue by Davka** [marcelkipp/ePortfolio#138]
![screenshot 2018-03-07 16 29 15](https://user-images.githubusercontent.com/1117697/37100980-b2ded914-2224-11e8-9ee7-67682247254c.png)

**Comment by asudau** [comment]
hmm ja das habe ich bei mir im chromium auch, im firefox sieht alles normal aus..
nehme ich mal unter die Lupe!

**Comment by asudau** [comment]
ich schließe das mal erstmal..
