### ISSUE TITLE
Vorlage verteilen

### ISSUE THREAD

**Issue by Davka** [marcelkipp/ePortfolio#139]
Fehlt hier was?

![screenshot 2018-03-07 16 31 24](https://user-images.githubusercontent.com/1117697/37101097-020dcf40-2225-11e8-95d9-b4e6746a1969.png)

**Comment by asudau** [comment]
sind in der Gruppe schon Nutzer? Da braucht es vermutlich etwas mehr an Feedback, also Abfangen wenn keine Nutzer da sind mit entsprechendem Hinweis!

**Comment by asudau** [comment]
beim testen fällt mir grad auf, derzeit tragen wir Nutzer direkt als dozenten in ihr portfolio ein, das passt natürlich nich twenn nutzer global nur autoren sind, das muss ich mir nochmal ansehen, mich wundert dass das überhaupt ging..
