### ISSUE TITLE
Aktionen nicht klar

### ISSUE THREAD

**Issue by Davka** [marcelkipp/ePortfolio#152]
Die Plus-Icons sind nicht wirklich klar. Entweder eine Beschreibung hinzufügen, in die Sidebar als Aktion oder besser das jeweilige Plus in die <caption></caption> der Tabelle  verschieben
<img width="303" alt="screenshot 2018-03-15 10 48 57" src="https://user-images.githubusercontent.com/1117697/37455920-88cc77ce-283e-11e8-965b-1e6aabba5171.png">

**Comment by asudau** [comment]
da bin wohl ich für verantwortlich :-P vorher waren das Buttons mit Text drauf, ist vllt. auch besser, machen wir an anderen Stellen auch so, zB. beim hinzufügen von Nutzern an verschiedenen Stellen

**Comment by asudau** [comment]
Wir könnten die Aktionen auch einfach als Aktionen in die Sidebar packen..

**Comment by asudau** [comment]
Vielleicht beides, Aktionen in der Sidebar und das Plus in den Header der jeweiligen Tabelle
