### ISSUE TITLE
Kleinigkeit

### ISSUE THREAD

**Issue by Davka** [marcelkipp/ePortfolio#153]
<td class="actions"></td> Die Icons werden dann nach rechts geschoben :)

<img width="119" alt="screenshot 2018-03-15 10 50 46" src="https://user-images.githubusercontent.com/1117697/37456037-c670b41e-283e-11e8-99e0-5b41e925d103.png">

**Comment by asudau** [comment]
Hmm dieses Ticket versteh ich nicht ganz.. hängt das mit dem anderen zu den Plus-Buttons zusammen? Oder geht es nur um die Positionierung der Icons? Ich finde hier könnte man über den Seitenaufbau eh nochmal nachdenken.. Wenn es langfristig bei nur einer Aktion bleibt, würde ja eigentlich auch eine Verlinkung des Vorlagen-/Portfoliotitels in die jeweilige Veranstaltung reichen..
