### ISSUE TITLE
Gruppe löschen

### ISSUE THREAD

**Issue by Davka** [marcelkipp/ePortfolio#154]
In der Supervisorsicht sehe ich den Button "Gruppe löschen". Zunächst weiß ich nicht worauf sich dieser Button genau bezieht. Klicke ich drauf, dann erhalte ich eine SQL-Exception

`
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '18a2db235c0231581d5055e2f19196e0' at line 1`

**Comment by asudau** [comment]
Ja da ist im Testsystem noch ein Bug, habe ich auch gerade gemerkt, muss ich noch Updaten.
Den Knopf würde ich (ähnlich wie bei dem Plus-Icon-Ticket) als Aktion in die Sidebar verschieben, das würde dann etwa so aussehen:
![grafik](https://user-images.githubusercontent.com/11834384/37464160-d4dbb9b8-2857-11e8-8c4e-575c01e7b3e6.png)

**Comment by asudau** [comment]
was mir nicht so gut gefällt ist, das es dann zwei active links gäbe, den für den Supervisorbereich und den für die aktuell ausgewählte Gruppe.. Da muss ich nochmal drüber nachdenken..

**Comment by asudau** [comment]
ist im Testsystem aktualisiert und die Navigation schon etwas umgestrickt
