### ISSUE TITLE
Supervisorengruppen verwalten

### ISSUE THREAD

**Issue by Davka** [marcelkipp/ePortfolio#155]
Ich habe nun einige Gruppen gelöscht (Welche weiß ich nicht).

Klicke ich nun auf "Verwalten", dann erhalte ich 

`Fehler! Bitte wenden Sie sich an Ihren Systemadministrator. Fehler: Konnte das Seminar mit der ID nicht finden!`

**Comment by asudau** [comment]
ich fürchte das hängt mit dem von dir beschriebenen SQL Fehler beim löschen von Gruppen zusammen, dadruch wird der Prozess nicht sauber abgeschlossen. Ich will aber generell noch ein bisschen besseres Exception Handling einbauen damit in solchen fällen nciht immer das ganze System streikt.

**Comment by asudau** [comment]
sollte jetzt laufen
