### ISSUE TITLE
Fortschrittsanzeige (Portfoliobearbeitung)

### ISSUE THREAD

**Issue by asudau** [marcelkipp/ePortfolio#184]
das einzige was hier sinn macht ist die anzahl der möglichen freigaben mit den tatsächlichen freigaben zu vergleichen. Um das ganze etwas feingranularer hinzubekommen wäre es evtl sinnvoll jetzt die freigaben auf unterkapitelebene umzusetzen.  
Ggf könnte man auch ähnlich wie beim Sperren von Blöcken zur Bearbeitung in der Vorlage markieren welche Unterkapitel vom Studierenden bearbeitet/freigegeben werden müssen.

**Comment by marcelkipp** [comment]
Erstmal abschließen bis genauer Anforderungen da sind
