### ISSUE TITLE
getStatusOfUserInTemplate($user_id, $template_id, $group_id, $seminar_id){

### ISSUE THREAD

**Issue by asudau** [marcelkipp/ePortfolio#197]
die $user_id benutzen wir gar nicht und in der view zu memberdetail wird die zwar verwendet, ist aber nicht gesetzt..  
$user ist dort auch nicht gesetzt

**Comment by asudau** [comment]
$user variable an memberdetail übergeben und in zeile  LastVisited::chapter_last_visited die id übergeben

**Comment by asudau** [comment]
ich meinte hier die memberdetail action im showsupervisor-controller und die zugehörige view

**Comment by marcelkipp** [comment]
Nehmen wir erstmal ganz raus
