### ISSUE TITLE
XSS Vorlage erstellen

### ISSUE THREAD

**Issue by Davka** [marcelkipp/ePortfolio#207]
Die Felder Name und Beschreibung werden nicht gegen XSS geschützt

**Comment by asudau** [comment]
man wie sich das wieder eingeshclichen hat, da fällt einem nix zu ein!! Die Reparatur Schaff ich heut leider nicht mehr hoffentlich morgen früh fix

**Comment by asudau** [comment]
hab das strip_tags natürlich schön zusammen mit dem utf8decode rausgeworfen :-P
