### ISSUE TITLE
Kopierfunktion für Vorlagen

### ISSUE THREAD

**Issue by marcelkipp** [marcelkipp/ePortfolio#3]
Ron fragen: Import/Export aus DFB-Plugin

**Comment by marcelkipp** [comment]
Alter Inhalte in dem neu erstellten Veranstaltung löschen. (Kapitel 1 / Kapitel 2)

**Comment by marcelkipp** [comment]
supervisor-id mit Eintragen

**Comment by asudau** [comment]
Hinweis: Nutzen von Import und Export schlug zunächst fehl weil es in der neuen Veranstaltung keinen allgemeinen Dateibereich gab. [commit](https://github.com/marcelkipp/ePortfolio/commit/4bbe7455f813442584e568eca88b0efea33a3a59)  
  
Hier fehlt noch das Löschen der leeren Kapitel 1 und 2
