### ISSUE TITLE
Vorlagen: Bilder für Kapitel einstellen

### ISSUE THREAD

**Issue by marcelkipp** [marcelkipp/ePortfolio#42]
Dozenten sollen in der der Vorlagen-Veranstaltung Bilder für die einzelnen Kapitel hinzufügen können

**Comment by asudau** [comment]
julia und stefanie werden sich zu diesem punkt nochmal Gedanken machen und dann Feedback geben wie das langfristig aussehen soll, wenn es soweit ist machen wir ein neues Ticket auf
