### ISSUE TITLE
User von Gruppe löschen

### ISSUE THREAD

**Issue by marcelkipp** [marcelkipp/ePortfolio#58]
User von Gruppe löschen erst nach dem Refresh/neuladen ohne Parameter an URL möglich, nur wenn Gruppe neu erstellt wurde

**Comment by asudau** [comment]
Ist möglich, solange noch keine Portfolios an die Gruppe verteilt wurden. Ob das auch danach noch möglich sein soll muss ggf. noch geklärt werden (was passiert dann mit einem ggf. schon verteilten Portfolio und den zugehörigen Freigaben, etc.)
