### ISSUE TITLE
UTF-8-Probleme

### ISSUE THREAD

**Issue by tthelen** [marcelkipp/ePortfolio#63]
- Einige Textausgaben, z.B. "Lesen dürfen"
- Kursinhalte gehen beim Kopieren kaputt

**Comment by asudau** [comment]
Wir haben derzeit zwei Fälle in denen das Encoding kaputt geht. Das ein ist der reine Quellcode, wenn beim Editieren nicht im richtigen Encoding editiert wird (windows1252)  
Das andere sind Formulareingaben (Name meines Portfolios etc.) Wenn diese per Ajax weitergegeben werden, muss dort wo sie ankommen einmal _studip_utf8decode()_ drum rum gesetzt werden.

**Comment by asudau** [comment]
Es fehlt noch die Behandlung der Formulareingaben/ajax-calls

**Comment by asudau** [comment]
die courseware ist auch noch betroffen
