### ISSUE TITLE
Kommentarfunktion für Supervisoren in NotizSupervisor-Block

### ISSUE THREAD

**Issue by tthelen** [marcelkipp/ePortfolio#70]
Ron fragen wg. Umsetzung

Supervisoren sollen Kommentar in Notiz-Block "Supervisor" hinterlassen können

**Comment by asudau** [comment]
das ist jetzt in eriner ersten Version auf dem Testsystem verfügbar.  
Ansehen kann man das zB hier (einfach einmal als test_autor und einmal als test_dozent einloggen):  
https://studip3g-test-1.rz.uni-osnabrueck.de/studip/portfolio/plugins.php/courseware/courseware?cid=d3af0bf31d771a8e560cbc914875d3ef&selected=3548  

Hinweis: der Supervisor hat lnagfristig keine generellen Editierrechte in der Courseware eines Studierenden. Das Kommentarfeld für den Supervisor ist somit erstmal im 'Lesemodus' schreibbar.

**Comment by asudau** [comment]
fixed in courseware https://github.com/virtUOS/courseware/tree/portfolio
