### ISSUE TITLE
Datenbanktabellen: Primärschlüssel setzen

### ISSUE THREAD

**Issue by tthelen** [marcelkipp/ePortfolio#75]
Die vom Plugin angelegten Datenbank-Tabellen haben keine Primärschlüssel.

**Comment by asudau** [comment]
jep habe mich auch etwas gewundert weil es in unserem Testsystem auch keine primärschlüssel gibt wenn ich das richtig gesehen habe (kann grad nicht drauf zugreifen). Dachte das macht nix aber werde mal ne Migration schreiben. Gibt das denn im Betrieb Schwierigkeiten? Das hab ich dann nämlich übersehen.

**Comment by marcelkipp** [comment]
Im Betrieb selber gibt es keine Schwierigkeiten. In phpmyadmin lassen sich die Einträge, aufgrund der fehlenden Primärschlüssel, nicht von Hand bearbeiten.

**Comment by asudau** [comment]
oh ja, das ergibt sinn!
