### ISSUE TITLE
Fehlermeldung - userbild nicht gefunden

### ISSUE THREAD

**Issue by asudau** [marcelkipp/ePortfolio#78]
GET https://studip3g-test-1.rz.uni-osnabrueck.de/studip/portfolio/pictures/user/c06a4f912a82532c6bfa09e16d72a679_medium@2x.png 404 (Not Found)

**Comment by asudau** [comment]
Hat das was mit dem Ticket zu den Avataren zu tun?

**Comment by marcelkipp** [comment]
Nein, das "Avatar"-Ticket bezog sich nur darauf, das Testsystem für Vechta nicht so "nackt" aussehen zu lassen. Da gibt es wohl ein Script von Marcus, was automatisch Nutzerbilder generiert

**Comment by asudau** [comment]
fixed
